### ISSUE TITLE
Collaboration request

### ISSUE THREAD

**Issue by johannes-graeter** [olympus-robotics/hephaestus#84]
Hi
I would like to contribute :) 
Would it make sense to convert the drafts to issues in https://github.com/orgs/olympus-robotics/projects/2/views/1?pane=issue&itemId=67106003
so that I can comment on them or carify requirements and questions?

Looking forward!

**Comment by johannes-graeter** [comment]
@filippobrizzi @lhruby

**Comment by filippobrizzi** [comment]
I converted all the drafts to issue and I invited you to the organisation
